name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate TG Config from Secrets
        env:
          TG_BOT_TOKEN: ${{ secrets.TOKEN }}
          TG_CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          mkdir -p js
          cat <<EOF > js/config.js
          window.TG_CONFIG = {
              BOT_TOKEN: '$TG_BOT_TOKEN',
              CHAT_ID: '$TG_CHAT_ID'
          };
          EOF

      # Дальше идет ваш шаг деплоя (например, GitHub Pages, хостинг, S3 и т.д.)
      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
